#prefix
set-option -g prefix C-g
unbind-key C-b

#buffer
set-option -g history-limit 10000

#reload conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# escape key delay
set -sg escape-time 1

#status
setw -g status-fg white
setw -g status-bg black
#setw -g windows-status-current-fg black
#setw -g windows-status-current-fg cyan

#key
bind c new-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"
bind s split-window -vc "#{pane_current_path}"
bind v split-window -hc "#{pane_current_path}"
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R
bind -r < resize-pane -L 1
bind -r > resize-pane -R 1
bind -r - resize-pane -D 1
bind -r + resize-pane -U 1
bind : command-prompt
bind C-i select-pane -t :.+
bind Escape copy-mode

setw -g mode-keys vi
 
#option set -g display-time 6000
set -g status-interval 30
set -g history-limit 5000

# mouse
#set -g mouse on
 
#status line
set -g status-right "#(w | head -1 | cut -d, -f4) | %Y/%m/%d (%a) %p %I:%M"
setw -g window-status-format "#I:#W"
setw -g window-status-current-format "#I:#W_#P"
set -g status-bg black
set -g status-fg cyan
#set -g status-left-fg black
#set -g status-left-bg magenta
#set -g status-right-fg black
#set -g status-right-bg green
#set-window-option -g window-status-current-attr bright,reverse
#set-window-option -g window-status-current-bg cyan
#set-window-option -g window-status-current-fg black
set-window-option -g xterm-keys on
set-option -g default-terminal "screen-256color"
#set -g default-terminal "screen-256color"
#set -g terminal-overrides 'xterm:colors=256'

#bind-key -t vi-copy [ begin-selection
#bind-key -t vi-copy C-v rectangle-toggle

#bind -t vi-copy Enter copy-pipe "xclip -i -selection clipboard"
#bind -t vi-copy Y select-line
#bind y run 'tmux copy-mode\; send-keys Y Enter'

#bind -t vi-copy Y copy-line
#bind y run 'tmux copy-mode\; send-keys Y'
#
#bind -t vi-copy V begin-selection
#bind v run 'tmux copy-mode\; send-keys ggVG Enter'

#bind -t vi-copy C-q copy-pipe "cat >/tmp/out"
